"""Project Mangal — Autonomous Causal Chain Compiler.

Translates the distilled Root Cause Axiom and Mutated Hypotheses into a 100% schema-valid
YAML causal prerequisite specification compatible with the Universal Inverse Design engine.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

from mangal_engine.distiller.axiom_distiller import DistilledAxiom
from mangal_engine.mutation.axiomatic_challenge import ChallengedHypothesis


@dataclass(frozen=True)
class CompiledChainResult:
    """The result of an autonomous chain compilation."""
    target_slug: str
    yaml_content: str
    file_path: Path
    node_count: int
    is_valid: bool


class ChainWriter:
    """Compiles distilled axioms and challenge hypotheses into valid UID causal chain YAMLs."""

    def _slugify(self, text: str) -> str:
        """Convert human text into a clean snake_case slug."""
        text = text.lower().strip()
        text = re.sub(r"[^\w\s-]", "", text)
        return re.sub(r"[-\s]+", "_", text)[:40].strip("_")

    def compile_chain(
        self,
        seed_problem: str,
        axiom: DistilledAxiom,
        hypotheses: Sequence[ChallengedHypothesis],
        output_dir: Path | str = "src/uid_engine/chains",
    ) -> CompiledChainResult:
        """Synthesizes and validates a production YAML causal chain."""
        target_slug = self._slugify(seed_problem)
        name_title = seed_problem.strip().title()

        # Find breakthrough mechanisms
        h1 = hypotheses[0].breakthrough_mechanism if len(hypotheses) > 0 else "De novo catalytic cleavage"
        h2 = hypotheses[1].breakthrough_mechanism if len(hypotheses) > 1 else "Precursor interception"
        h3 = hypotheses[2].breakthrough_mechanism if len(hypotheses) > 2 else "Targeted degradation"
        h4 = hypotheses[3].breakthrough_mechanism if len(hypotheses) > 3 else "ECM remodeling"

        # Build clean YAML structure matching CausalChainRegistry schema
        yaml_lines = [
            f"# Auto-generated by Project Mangal (mangal_engine v0.1.0)",
            f"# Root Cause Axiom: {axiom.axiom_id}",
            f'# Statement: "{axiom.core_axiom_statement}"',
            f"",
            f'name: "{name_title} Repair"',
            f'version: "1.0"',
            f'target: "{target_slug}"',
            f'goal: "Restore physiological compliance and functional homeostasis in {name_title}"',
            f'description: >',
            f'  Autonomous inverse design target derived via Project Mangal multi-dimensional interrogation.',
            f'  Root Cause: {axiom.core_axiom_statement}',
            f"",
            f"nodes:",
            f'  - id: "goal:{target_slug}_restoration"',
            f'    description: "Complete functional restoration and damage resolution in {name_title}"',
            f"    priority: CRITICAL",
            f"    children:",
            f'      - id: "req:selective_catalyst"',
            f'        description: "{h1}"',
            f'        required_graph_entity: "unknown:selective_catalyst"',
            f'        required_edge_type: "DEGRADES"',
            f'        required_status: "PROVEN"',
            f"        priority: CRITICAL",
            f"        children:",
            f'          - id: "req:catalytic_active_site"',
            f'            description: "3D complementary active site geometry for transition-state stabilization"',
            f'            required_graph_entity: "unknown:catalytic_pocket"',
            f'            required_edge_type: "CATALYZES"',
            f'            required_status: "PROVEN"',
            f"            priority: HIGH",
            f'          - id: "req:protein_scaffold"',
            f'            description: "Stable protein scaffold supporting catalytic geometry (pLDDT >= 85.0)"',
            f'            required_graph_entity: "unknown:homologous_scaffold"',
            f'            required_edge_type: "REQUIRES"',
            f'            required_status: "PROVEN"',
            f"            priority: HIGH",
            f'      - id: "req:in_vivo_delivery"',
            f'        description: "{h2}"',
            f'        required_graph_entity: "unknown:delivery_vector"',
            f'        required_edge_type: "REQUIRES"',
            f'        required_status: "PROVEN"',
            f"        priority: HIGH",
            f"        children:",
            f'          - id: "req:tissue_penetration"',
            f'            description: "Capacity to penetrate dense tissue extracellular matrix without premature clearance"',
            f'            required_graph_entity: "unknown:penetration_domain"',
            f'            required_edge_type: "REQUIRES"',
            f'            required_status: "PROVEN"',
            f"            priority: HIGH",
            f'          - id: "req:serum_stability"',
            f'            description: "Resistance to endogenous protease degradation and low immunogenicity (GRAVY <= 0.2)"',
            f'            required_graph_entity: "unknown:serum_stabilizer"',
            f'            required_edge_type: "REQUIRES"',
            f'            required_status: "PROVEN"',
            f"            priority: MEDIUM",
            f'      - id: "req:safety_validation"',
            f'        description: "{h3} while ensuring {h4}"',
            f'        required_graph_entity: "unknown:safety_assay"',
            f'        required_edge_type: "BLOCKS"',
            f'        required_status: "PROVEN"',
            f"        priority: HIGH",
            f"        children:",
            f'          - id: "req:off_target_cleavage_screen"',
            f'            description: "Verification that native structural biomolecules remain undamaged"',
            f'            required_graph_entity: "unknown:off_target_screen"',
            f'            required_edge_type: "BLOCKS"',
            f'            required_status: "PROVEN"',
            f"            priority: MEDIUM",
            f'          - id: "req:byproduct_toxicity"',
            f'            description: "Confirmation that cleavage reaction byproducts are non-toxic and metabolizable"',
            f'            required_graph_entity: "unknown:toxicity_profile"',
            f'            required_edge_type: "BLOCKS"',
            f'            required_status: "PROVEN"',
            f"            priority: MEDIUM",
            f"",
        ]

        yaml_content = "\n".join(yaml_lines)

        # Write to destination
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_file = out_dir / f"{target_slug}.yaml"
        out_file.write_text(yaml_content, encoding="utf-8")

        # Validate with CausalChainRegistry if available
        is_valid = True
        try:
            from uid_engine.chains.registry import CausalChainRegistry
            registry = CausalChainRegistry()
            registry.load_from_path(out_file)
        except Exception:
            is_valid = False

        node_count = yaml_content.count("id: \"")

        return CompiledChainResult(
            target_slug=target_slug,
            yaml_content=yaml_content,
            file_path=out_file,
            node_count=node_count,
            is_valid=is_valid,
        )
